/**
 * editorial.mjs — the judgement layer of the indigo data file.
 *
 * Evidence lives in research/*.json. This file decides what the page shows
 * and how it is framed: era boundaries, which events are mapped, the
 * narrative steps, chart declarations, the sankey models and the two
 * tables. Every figure quoted in prose here is taken from a research record,
 * and the record's own source object travels with it through the helpers
 * (H.eventSources, H.quantSources, H.seriesPoint). tools/build-data.mjs
 * compiles the result into js/data.js.
 */

export default function editorial(H) {
  const ev  = (id, idx) => H.eventSources(id, idx);
  const qs  = (id, idx) => H.quantSources(id, idx);
  const pt  = (id, year) => H.seriesPoint(id, year).source;

  /* ── ERAS ─────────────────────────────────────────────────────────
     Eight named periods. Each opens at a cited turning point, named in its
     note; the boundaries themselves are an editorial reading (DERIVED). */
  const eras = [
    { slug: 'origins',    label: 'Ancient',    name: 'Ancient Blue',            start: -4500, fallback: '#C9A46E',
      note: 'Opens with the oldest dated indigo-dyed cloth: cotton from Huaca Prieta, Peru, about 6,200–6,000 years old.' },
    { slug: 'medieval',   label: 'Medieval',   name: 'Guilds & Caravans',       start: 500,   fallback: '#CDBE5E',
      note: 'Opens around China\'s first written indigo recipe, the Qimin yaoshu of c. 544 CE; boundary rounded to 500.' },
    { slug: 'searoutes',  label: 'Sea Routes', name: 'Sea Routes & Woad Wars',  start: 1498,  fallback: '#6CB2BA',
      note: 'Opens with Vasco da Gama at Calicut, 20 May 1498.' },
    { slug: 'plantation', label: 'Plantation', name: 'Plantation Blue',         start: 1650,  fallback: '#A58BD6',
      note: 'Opens with Saxony\'s 1650 ban aimed at indigo itself, as the Caribbean and Carolina plantation supply rose.' },
    { slug: 'empire',     label: 'Empire',     name: 'Empire Blue',             start: 1790,  fallback: '#E0645A',
      note: 'Opens as Bengal takes over from the Atlantic; the Bengal output series begins in 1795.' },
    { slug: 'synthetic',  label: 'Synthetic',  name: 'Synthetic Shock',         start: 1897,  fallback: '#A3AAB9',
      note: 'Opens with BASF\'s synthetic Indigo Pure on sale, 10 July 1897.' },
    { slug: 'denim',      label: 'Denim',      name: 'Denim Century',           start: 1946,  fallback: '#7F9BEA',
      note: 'Opens after the Second World War, when US soldiers had carried jeans abroad and indigo became a denim dye.' },
    { slug: 'revival',    label: 'Revival',    name: 'Revival & Reckoning',     start: 2000,  fallback: '#86C08F',
      note: 'Opens with the 2000 US anti-dumping order on Chinese indigo, the marker of production\'s move to China.' },
  ];

  const meta = {
    title: 'Indigo: A Global Commodity Autopsy',
    subtitle: 'Six thousand years of the world\'s blue, from a Peruvian midden to the denim mill',
    asOfYear: 2025,
    center: [22, 30],
    defaultZoom: 2,
    eras,
    /* Compressed time: [slider position, year] knots, linear between. */
    timeKnots: [[0, -4500], [250, 500], [450, 1500], [1000, 2025]],
    axisTicks: [-4000, -2000, 1, 1000, 1500, 1600, 1700, 1800, 1900, 2000],
    sliderTicks: [
      { year: -4500, label: '4500 BCE' }, { year: -2000, label: '2000 BCE' }, { year: 500, label: '500 CE' },
      { year: 1000, label: '1000' }, { year: 1498, label: '1498' }, { year: 1650, label: '1650' },
      { year: 1790, label: '1790' }, { year: 1897, label: '1897' }, { year: 2025, label: '2025' },
    ],
    sliderStartYear: -4500,
    continents: ['Americas', 'Europe', 'Africa', 'West Asia', 'South Asia', 'East Asia'],
    sliderCards: [
      { id: 'stat-carolina',      series: 'sc-exports',     label: 'South Carolina exports',        suffix: ' lb',     color: 'plantation', maxGap: 1 },
      { id: 'stat-bengal',        series: 'bengal-output',  label: 'Bengal output',                  suffix: ' maunds', color: 'empire',     maxGap: 1 },
      { id: 'stat-india-area',    series: 'india-area',     label: 'British India area under indigo', suffix: ' acres', color: 'v7',         maxGap: 1 },
      { id: 'stat-india-exports', series: 'india-exports',  label: 'British India exports',          suffix: ' cwt',    color: 'synthetic',  maxGap: 1 },
    ],
  };

  /* ── MAPPED EVENTS ────────────────────────────────────────────────
     Ids from research/*.json. Where two research slices covered the same
     event, one record is chosen here. Overrides change wording only. */
  const events = [
    // Ancient
    'huaca-prieta-indigo-cotton',
    { id: 'egypt-fifth-dynasty-blue-linen', title: 'Egypt\'s earliest reported indigo-dyed linen', lat: 29.87, lng: 31.22,
      place: 'Egypt, Old Kingdom (Fifth Dynasty); findspot not named in the sources — marker at Saqqara-Memphis' },
    { id: 'beycesultan-woad-nalbinding', continent: 'West Asia' },
    'tutankhamun-indigo-linen',
    { id: 'hallstatt-woad-textiles', year: -1200, date: 'Bronze and Iron Ages (c. 1500–400 BCE)' },
    'babylonian-dye-recipe-tablet',
    'xunzi-blue-from-indigo',
    'caesar-britons-vitrum',
    { id: 'maya-blue-calakmul', date: 'Late Preclassic (plotted at 100 BCE, a period midpoint)' },
    'periplus-barbarikon-indigo',
    'pliny-indicum-price',
    { id: 'diocletian-price-edict-indigo', continent: 'West Asia' },
    // Medieval
    'qimin-yaoshu-indigo-paste',
    'shosoin-knotweed-indigo',
    'capitulare-de-villis-woad',
    'oseberg-woad-seeds',
    'york-coppergate-dyers',
    'geniza-indigo-trade',
    { id: 'chichen-itza-maya-blue-ritual', year: 1000, date: 'c. 600–1200 CE (plotted at 1000)' },
    'gujarat-indigo-cottons-egypt',
    'tellem-indigo-textiles',
    'benjamin-tudela-jewish-dyers',
    'amiens-woad-cathedral',
    'zhao-rugua-gujarat-indigo',
    'marco-polo-coilum-indigo',
    'erfurt-woad-towns-university',
    'toulouse-pastel-golden-age',
    // Sea routes
    'kofar-mata-dye-pits-1498',
    'da-gama-reaches-calicut',
    'toulouse-pastel-boom-and-bust',
    'reichspolizeiordnung-teufelsfarb-1577',
    'elizabethan-dye-statute-1581',
    'guatemala-indigo-labor-law-1581',
    'languedoc-indigo-ban-1598',
    'central-america-xiquilite-obrajes-1600',
    'indigo-currency-guatemala-1624',
    'bayana-indigo-pelsaert-1626',
    'voc-indigo-fleet-1631',
    'quinones-autos-1636',
    // Plantation
    'imperial-indigo-ban-1654',
    'colbert-dye-statutes-1669',
    'jamaica-indigo-works-1670',
    'awa-indigo-dominates-japan',
    'labat-indigoterie-french-antilles',
    'eliza-lucas-wappoo-1744',
    'carolina-provincial-bounty-first-exports-1747',
    'parliament-indigo-bounty-1748',
    'enslaved-indigo-makers-carolina',
    'georgia-indigo-exports-1755',
    { id: 'guinea-cloth-slave-trade-1765', lat: 16.03, lng: -16.50,
      place: 'West African coast — marker at Saint-Louis on the Senegal River, where Indian cloth became a currency; the 1765 order went from East India House, London, to Calcutta' },
    'east-florida-new-smyrna-1768',
    'saint-domingue-indigo-peak-1771',
    'carolina-indigo-peak-1775',
    { id: 'mouzon-map-indigo-vignette-1775', lat: 33.2, lng: -80.0, place: 'The Carolinas (map published in London, 1775)' },
    'company-revives-bengal-indigo',
    'revolution-ends-indigo-bounty-1777',
    'guatemala-indigo-merchants-1778',
    'montepio-cosecheros-anil-1782',
    'bengal-indigo-reaches-england-1786',
    'saint-domingue-3150-indigoteries-1789',
    // Empire
    'louisiana-indigo-caterpillars-1793',
    'bengal-indigo-output-peak-1825',
    'ryoti-advance-system',
    'barth-kano-cloth-trade-1851',
    'tuareg-indigo-litham',
    'indigo-revolt-1859',
    'indigo-act-and-commission-1860',
    'nil-darpan-1860',
    'james-long-trial-1861',
    'industry-moves-to-bihar-tinkathia',
    'levi-strauss-davis-rivet-patent',
    'baeyer-first-indigo-synthesis',
    'heumann-syntheses-mercury-catalyst',
    'indian-indigo-peak-1895',
    // Synthetic
    'basf-indigo-pure-launch',
    'synthetic-shock-planters-research-1897',
    'pfleger-sodamide-process',
    'indigo-factories-halve-1901-1903',
    'awa-indigo-peak-1903',
    'japan-raises-duty-on-indian-indigo-1903',
    'cone-white-oak-opens',
    'baeyer-nobel-prize',
    'basf-hydrosulfite-vatting',
    'adire-eleko-abeokuta',
    'german-synthetic-indigo-peak-1913',
    'india-natural-indigo-collapse',
    'wwi-indigo-revival-1915',
    'champaran-satyagraha-1917',
    'champaran-agrarian-act-1918',
    'japan-buys-indian-indigo-1921',
    'post-war-collapse-1924',
    'adire-collapse-1930s',
    // Denim
    'jeans-go-global',
    'japanese-denim-kurabo-kaihara',
    'microbial-indigo-e-coli',
    'dystar-prereduced-indigo',
    // Revival
    'us-antidumping-chinese-indigo',
    'nantong-blue-calico-heritage-2006',
    'danzhai-miao-batik-2006',
    'sakon-nakhon-indigo-gi-2006',
    'tehuacan-blue-water',
    'living-blue-rangpur',
    'indonesian-batik-unesco-2009',
    'lesotho-denim-effluent',
    'xintang-pearl-river-pollution',
    'stony-creek-colors',
    'levis-501-lifecycle-assessment',
    'tokyo-2020-indigo-emblem',
    'cone-white-oak-closes',
    'champaran-centenary-2017',
    'hsu-indican-dyeing',
    'archroma-aniline-free-indigo',
    { id: 'unesco-blaudruck-inscription', lat: 48.21, lng: 16.37, place: 'Austria, Czechia, Germany, Hungary and Slovakia (marker at Vienna; inscribed at Port Louis, Mauritius)' },
    'dhaka-savar-black-rivers',
    'dystar-ludwigshafen-closure',
    'tokushima-sukumo-2024',
  ];

  /* ── NARRATIVE STEPS ─────────────────────────────────────────────── */
  const scrollSteps = [
    { eventId: 'huaca-prieta-indigo-cotton', date: 'c. 4200 BCE', zoom: 5,
      media: ['anil-indigofera-suffruticosa'],
      headline: 'The first blue is American',
      narrative: 'The oldest indigo-dyed cloth yet found comes not from India, Egypt or China but from Huaca Prieta, a mound on Peru\'s north coast. Chemists identified indigotin in cotton about 6,200–6,000 years old — more than 1,500 years before the earliest reported Old World example. The dye most likely came from an Indigofera native to South America.',
      chips: [{ label: 'Age', value: '≈6,200–6,000 yrs' }, { label: 'Fibre', value: 'cotton' }, { label: 'Found by', value: 'HPLC, 2016' }] },
    { eventId: 'tutankhamun-indigo-linen', date: 'c. 1323 BCE', zoom: 5,
      media: ['tutankhamun-blue-kerchief', 'egypt-vine-scroll-band-indigotin'],
      headline: 'Blue in the pharaoh\'s linen',
      narrative: 'Egypt\'s earliest reported indigo-dyed linen is dated to the Fifth Dynasty, about 2400 BCE, though the sources do not name a findspot or a plant. The evidence firms up in Tutankhamun\'s tomb: a 2023 spectroscopic study found both indigo and madder on a linen fragment. The method identifies the molecule, not the plant — Egypt had both woad and Indigofera within reach.',
      chips: [{ label: 'Burial', value: 'c. 1323 BCE' }, { label: 'Dyes found', value: 'indigo + madder' }, { label: 'Plant', value: 'undetermined' }] },
    { eventId: 'babylonian-dye-recipe-tablet', date: '7th century BCE', zoom: 5,
      headline: 'A dyer\'s recipe on clay',
      narrative: 'A Late Babylonian tablet in the British Museum records recipes for wool dyed pale or dark blue by repeated immersion, then over-dyed with madder to imitate the prestige purples. It already describes indigo\'s defining trick — depth by repetition — though it never names the blue plant; woad is a modern chemist\'s suggestion.',
      chips: [{ label: 'Tablet', value: 'BM 62788+82978' }, { label: 'Method', value: 'repeated dips' }] },
    { eventId: 'maya-blue-calakmul', date: 'Late Preclassic', zoom: 5,
      media: ['maya-blue-crocodile-whistle', 'bonampak-murals-maya-blue'],
      headline: 'Maya Blue: indigo locked in clay',
      narrative: 'In Mesoamerica indigo became a pigment as well as a dye. Bound to the clay mineral palygorskite it forms Maya Blue, stable enough to survive two thousand years of tropical weather. Its earliest known use is a Late Preclassic frieze at Calakmul; at Chichén Itzá it was later made in ritual beside the Sacred Cenote, whose floor was found coated in blue sediment.',
      chips: [{ label: 'Clay', value: 'palygorskite' }, { label: 'Earliest', value: 'Calakmul frieze' }] },
    { eventId: 'pliny-indicum-price', date: '77 CE', zoom: 3, flyTo: [25, 45],
      media: ['indigofera-tinctoria-plant'],
      headline: 'Indicum: a luxury from India, priced by the pound',
      narrative: 'Rome bought its indigo from India as indicum — the source of the word. The Periplus lists it among the exports of Barbarikon in the Indus delta; Pliny prices it at 20 denarii a pound and warns of fakes made from chalk stained with woad. In 301 CE Diocletian\'s price edict capped a pound of what is probably indigo at 750 denarii, close to the 800 allowed for pepper.',
      chips: [{ label: 'Pliny, 77 CE', value: '20 denarii/lb' }, { label: 'Edict cap, 301', value: '750 denarii/lb' }, { label: 'Pepper cap', value: '800' }] },
    { eventId: 'qimin-yaoshu-indigo-paste', date: 'c. 544 CE', zoom: 4,
      media: ['japanese-indigo-persicaria-tinctoria', 'nigatsudo-burned-sutra-indigo-paper'],
      headline: 'China writes the method down',
      narrative: 'Jia Sixie\'s farming manual of about 544 CE sets out the East Asian method: steep the cut plants in a lined pit, move the liquor to jars, add lime, beat it and keep the settled sediment as indigo paste. It also gives the economics — ten mu of indigo were worth a hundred mu of grain land. Centuries earlier Xunzi had made the plant a proverb: blue is taken from indigo, yet is bluer than it.',
      chips: [{ label: '10 mu of indigo', value: '= 100 mu grain' }, { label: 'Lime', value: '1.5% by volume' }] },
    { eventId: 'tellem-indigo-textiles', date: '11th–12th century', zoom: 5,
      headline: 'Blue in the Bandiagara cliffs',
      narrative: 'Cotton textiles from Tellem burial caves on Mali\'s Bandiagara Escarpment are the oldest known from sub-Saharan Africa. Some, dated to the eleventh or twelfth century, already carry stripes, checks and tie-dye patterns in indigo — from Indigofera or the West African Philenoptera, which chemical residues cannot tell apart.',
      chips: [{ label: 'Oldest cloth', value: 'sub-Saharan Africa' }, { label: 'Patterns', value: 'stripes, checks, tie-dye' }] },
    { eventId: 'marco-polo-coilum-indigo', date: 'c. 1293', zoom: 4,
      media: ['gujarat-stamp-resist-cotton', 'ehret-indigofera-tinctoria'],
      headline: 'Marco Polo watches it made',
      narrative: 'At Quilon (Kollam) on the Malabar coast Marco Polo described "abundance of very fine indigo": a herb steeped in great vessels until it rotted, the liquor set in the hot sun, the cake cut into four-ounce pieces for Europe. By then Gujarati indigo-resist cottons had been reaching Egypt for nearly three centuries, and a Chinese trade official recorded Gujarat\'s indigo shipped yearly to the Arab lands.',
      chips: [{ label: 'Cake', value: '4-oz pieces' }, { label: 'Earliest Gujarati cotton in Egypt', value: '1010 ± 55 CE' }] },
    { eventId: 'erfurt-woad-towns-university', date: '13th–16th centuries', zoom: 5, flyTo: [48.5, 6],
      media: ['bruges-dyers-1482', 'woad-cocagnes-toulouse'],
      headline: 'Woad builds cities',
      narrative: 'Europe\'s own blue was woad. Its trade helped pay for Amiens Cathedral (begun 1220), made Thuringia\'s five "woad towns" rich — Erfurt\'s university, founded in 1392, was "presumably" paid for with woad money — and from 1463 turned the Lauragais around Toulouse into the "pays de cocagne". Woad gives far less dye than tropical Indigofera: about a fifth, by a 2025 measurement.',
      chips: [{ label: 'Thuringian woad towns', value: '5' }, { label: 'Yield vs Indigofera', value: '≈1/5' }] },
    { eventId: 'da-gama-reaches-calicut', date: '20 May 1498', zoom: 3, flyTo: [12, 62],
      media: ['namban-screen-european-ship'],
      headline: 'The sea route',
      narrative: 'Vasco da Gama reached Calicut on 20 May 1498. No surviving invoice proves indigo was in the first cargoes, but the sea route let Asian indigo reach northern Europe in bulk without Venetian or Levantine middlemen; by 1516 Calicut price lists quoted "good indigo". In 1631 seven Dutch East India Company ships landed 333,545 lb of Gujarat and Bayana indigo in a single season.',
      chips: [{ label: 'Calicut', value: '20 May 1498' }, { label: 'VOC fleet, 1631', value: '333,545 lb' }] },
    { eventId: 'indigo-currency-guatemala-1624', date: '30 April 1624', zoom: 5,
      headline: 'Indigo as money — paid in people',
      narrative: 'In the Spanish Kingdom of Guatemala, añil made from the native xiquilite became both the main export and a currency. The Crown repeatedly barred Indigenous workers from the deadly fermentation vats and turned to enslaved Africans instead; enforcement was weak and owners paid the fines. On 30 April 1624 ten captives from Angola were sold in Santiago de Guatemala for 85 quintals of indigo.',
      chips: [{ label: 'Price per person', value: '8.5 quintals' }, { label: 'Labour bans', value: '1549 · 1581 · 1636' }] },
    { eventId: 'imperial-indigo-ban-1654', date: '1650–1654', zoom: 5,
      media: ['woad-isatis-bouchard-1770s', 'indigo-vat-plate-radel-benard'],
      headline: 'The "devil\'s dye" — and what the laws really said',
      narrative: 'Woad states fought imported indigo with law, but the famous 1577 imperial ban on a "devil\'s dye" targeted a vitriol-based colour, not indigo. The first ban aimed at indigo itself came from Saxony in 1650; an imperial prohibition followed on 21 April 1654, and Nuremberg\'s dyers swore an annual oath not to use it. France had banned indigo in 1598; Colbert\'s 1669 rules let it into fine dyeing.',
      chips: [{ label: '1577 "devil\'s dye"', value: 'vitriol, not indigo' }, { label: 'Indigo bans', value: 'Saxony 1650 · Empire 1654' }] },
    { eventId: 'enslaved-indigo-makers-carolina', date: '1747–1775', zoom: 5,
      media: ['faden-carolina-map-cartouche-1780', 'beauvais-raseau-art-indigotier-1770'],
      headline: 'Carolina\'s blue, made by enslaved hands',
      narrative: 'South Carolina\'s industry grew from the Wappoo trials of Eliza Lucas and others (1739–44), a provincial bounty, and from 1748 Parliament\'s sixpence a pound. Planting, harvesting and the skilled steeping and beating were done almost entirely by enslaved Africans; in 1755 Charles Woodmason reckoned 50 acres needed 15 hands to grow and 25 to process. The record entry, 1,122,200 lb in 1775, covers only 6½ months.',
      chips: [{ label: 'Bounty, 1748', value: '6d per lb' }, { label: '1775 entry', value: '1,122,200 lb (6½ mo.)' }, { label: 'Hands per 50 acres', value: '15 + 25' }] },
    { eventId: 'guinea-cloth-slave-trade-1765', date: '15 February 1765', zoom: 3, flyTo: [14, -8],
      media: ['indigo-manufactory-india-1778'],
      headline: 'Cloth that bought people',
      narrative: 'The two ends of the trade met on the West African coast. Indian cotton dyed with indigo — "blue goods", guinées, bafts and nicanees — was a key currency for buying enslaved people; Indian piece goods made up about 30% of Anglo-African export value in the mid-eighteenth century. On 15 February 1765 the East India Company asked Calcutta for more textiles for African markets.',
      chips: [{ label: 'Share of Anglo-African exports', value: '≈30%' }] },
    { eventId: 'saint-domingue-3150-indigoteries-1789', date: '1789', zoom: 5,
      media: ['antilles-indigoterie-1683'],
      headline: '3,150 indigo works on the eve of revolution',
      narrative: 'France\'s Saint-Domingue was the largest Atlantic producer. Moreau de Saint-Méry counted 3,150 indigoteries there in 1789 beside 793 sugar works, and its indigo shipments to France had topped four million livres in 1771–72. Indigo\'s low capital needs made it a path to planter status for free people of colour — but, like the sugar, it was made by enslaved labour.',
      chips: [{ label: 'Indigoteries, 1789', value: '3,150' }, { label: 'Sugar works', value: '793' }] },
    { eventId: 'indigo-revolt-1859', date: 'March 1859', zoom: 5,
      media: ['simpson-indigo-factory-bengal-1867', 'nil-darpan-title-page-1861'],
      headline: 'Bengal refuses to sow',
      narrative: 'After the Atlantic supply collapsed, the East India Company rebuilt Indian indigo in Bengal, where output reached 156,548 factory maunds in 1825–26. Ryots grew it under cash advances that trapped them in debt; a magistrate put 49 cases of murder, arson, kidnapping and other violence from 1830–59 before the 1860 Indigo Commission. In March 1859 Nadia\'s cultivators refused to sow, and the strike spread across Lower Bengal.',
      chips: [{ label: 'Bengal output, 1825–26', value: '156,548 maunds' }, { label: 'Serious cases, 1830–59', value: '49' }, { label: 'Nil Darpan', value: '1860' }] },
    { eventId: 'basf-indigo-pure-launch', date: '10 July 1897', zoom: 5,
      media: ['adolf-von-baeyer-portrait', 'basf-ludwigshafen-1881'],
      headline: 'Indigo Pure',
      narrative: 'Adolf von Baeyer first made indigo in a laboratory in 1878, but a factory route took BASF seventeen years and about 18 million gold marks. "Indigo Pure BASF" went on sale on 10 July 1897 at 16 marks a kilo, against 20 for refined natural indigo. By 1913 BASF and Hoechst together exported 10,000 tonnes.',
      chips: [{ label: 'On sale', value: '10 July 1897' }, { label: 'Price, 1897', value: '16 vs 20 marks/kg' }, { label: 'German exports, 1913', value: '10,000 t' }] },
    { eventId: 'champaran-satyagraha-1917', date: 'April 1917', zoom: 5,
      media: ['gandhi-1917-champaran', 'beating-indigo-vats-1877'],
      headline: 'Champaran',
      narrative: 'Synthetic indigo cut British India\'s indigo area from 1.7 million acres in 1894–95 to 146,000 in 1914–15, and its exports by 94% between 1895–96 and 1913–14. In Bihar, tenants under tinkathia still had to plant 3 of every 20 parts of their land with indigo. In April 1917 Gandhi went to Champaran; volunteers took nearly 4,000 statements, and the 1918 Agrarian Act abolished tinkathia.',
      chips: [{ label: 'Area, 1894–95', value: '1,705,977 acres' }, { label: 'Area, 1914–15', value: '146,000' }, { label: 'Tinkathia', value: '3/20 of land' }] },
    { eventId: 'jeans-go-global', date: '1940s–1965', zoom: 4,
      media: ['levi-strauss-davis-rivet-patent-1873', 'route-66-hitchhiker-1972'],
      headline: 'Denim takes the dye',
      narrative: 'Riveted work trousers were patented in 1873 by the Reno tailor Jacob Davis, assignor to himself and Levi Strauss & Co., and made from indigo-dyed denim. US soldiers carried jeans abroad in the Second World War; Levi\'s began exporting to Europe in 1959 and set up its international and Far East arms in 1965. BASF dates indigo\'s renaissance to the mid-1960s, and by 1997 denim absorbed 99% of all indigo made.',
      chips: [{ label: 'Patent 139,121', value: '20 May 1873' }, { label: 'Denim\'s share of indigo, 1997', value: '99%' }] },
    { eventId: 'xintang-pearl-river-pollution', date: '2010', zoom: 5,
      media: ['selvedge-denim-indigo-fades'],
      headline: 'The blue river',
      narrative: 'Denim moved to low-cost hubs, and the vats moved with it. In 2010 Xintang in Guangdong made about 200 million pairs of jeans a year; Greenpeace found heavy metals in 17 of 21 water and sediment samples from Xintang and Gurao, one with cadmium at 128 times China\'s limit. Similar reports followed from Tehuacán, Lesotho and Dhaka. Most indigo is now made in China; its birthplace at Ludwigshafen closed in 2023.',
      chips: [{ label: 'Xintang jeans, 2010', value: '≈200M pairs/yr' }, { label: 'Samples with metals', value: '17 of 21' }, { label: 'Cadmium', value: '128× limit' }] },
    { eventId: 'hsu-indican-dyeing', date: '2018', zoom: 4, flyTo: [38, -100],
      media: ['blaudruck-indigo-vat-austria', 'matsubara-nobuo-indigo-vat'],
      headline: 'Back to the plant — and to the microbe',
      narrative: 'The newest indigo borrows the plant\'s own trick. In 2018 a Berkeley team made E. coli produce indican, the leaf\'s protected precursor, so that dyeing needs neither aniline nor a reducing agent. Farms grow plant indigo again, from Tennessee\'s Stony Creek Colors to Bangladesh\'s Living Blue, and UNESCO listed Europe\'s indigo resist printing in 2018. Plant indigo is still estimated at about 1% of supply.',
      chips: [{ label: 'Natural share (estimate)', value: '≈1%' }, { label: 'Stony Creek, 2022', value: '≈500 acres' }, { label: 'Tokushima sukumo, FY2024', value: '37 t' }] },
  ];

  /* ── SERIES ──────────────────────────────────────────────────────── */
  const LB_T = 0.00045359237;
  const series = {
    'sc-exports':    { from: 'south-carolina-indigo-exports', label: 'South Carolina', unit: 'lb', geography: 'South Carolina (exports)' },
    'ga-exports':    { from: 'georgia-indigo-exports',        label: 'Georgia',        unit: 'lb', geography: 'Georgia (exports)' },
    'ca-output':     { from: 'central-america-indigo-output', label: 'Central America (Guatemala & San Salvador)', unit: 'libras (≈ lb)', geography: 'Kingdom of Guatemala',
                       note: 'Mixes harvest and export figures and period averages; the points are not one continuous series.' },
    'sd-to-france-lb': { from: 'saint-domingue-indigo-to-france', label: 'Saint-Domingue → France', unit: 'lb (converted)', geography: 'Saint-Domingue',
                       convert: { factor: 1.079, fromUnit: 'livres poids', note: 'Converted from French livres poids at 1 livre ≈ 0.4895 kg ≈ 1.079 lb.', round: 1 } },
    'arcahaye':      { from: 'arcahaye-indigoteries', label: 'Indigo works in L\'Arcahaye parish', unit: 'indigoteries', geography: 'Saint-Domingue' },
    'bengal-output': { from: 'bengal-indigo-production-1795-1832', label: 'Bengal output', unit: 'factory maunds', geography: 'Bengal and adjoining territories' },
    'bengal-output-t': { from: 'bengal-indigo-production-1795-1832', label: 'Bengal output (t)', unit: 'tonnes (converted)', geography: 'Bengal',
                       convert: { factor: 0.033868, fromUnit: 'factory maunds', note: 'Converted at 1 factory maund = 33.868 kg, the source\'s own equivalence.', round: 1 } },
    'india-area':    { from: 'british-india-indigo-area', label: 'Area under indigo, British India', unit: 'acres', geography: 'British India (official returns)' },
    'india-exports': { from: 'british-india-indigo-exports-cwt', label: 'Exports from British India', unit: 'cwt', geography: 'British India (all ports)' },
    'india-exports-t': { from: 'british-india-indigo-exports-cwt', label: 'British India exports (t)', unit: 'tonnes (converted)', geography: 'British India',
                       convert: { factor: 0.0508023, fromUnit: 'cwt', note: 'Converted at 1 cwt = 112 lb = 50.8 kg.', round: 1 } },
    'sc-exports-t':  { from: 'south-carolina-indigo-exports', label: 'South Carolina exports (t)', unit: 'tonnes (converted)', geography: 'South Carolina',
                       convert: { factor: LB_T, fromUnit: 'lb', note: 'Converted at 1 lb = 0.4536 kg.', round: 10 } },
    'ca-output-t':   { from: 'central-america-indigo-output', label: 'Central America (t)', unit: 'tonnes (converted)', geography: 'Kingdom of Guatemala',
                       convert: { factor: 0.00046, fromUnit: 'libras', note: 'Converted at 1 Spanish libra ≈ 0.46 kg; sources mix libras and English pounds.', round: 1 } },
    'sd-to-france-t': { from: 'saint-domingue-indigo-to-france', label: 'Saint-Domingue → France (t)', unit: 'tonnes (converted)', geography: 'Saint-Domingue',
                       convert: { factor: 0.0004895, fromUnit: 'livres poids', note: 'Converted at 1 livre poids ≈ 0.4895 kg.', round: 1 } },
    'uk-natural-gbp':   { from: 'uk-imports-natural-indigo-value',   label: 'Natural indigo', unit: '£ (nominal)', geography: 'United Kingdom imports' },
    'uk-synthetic-gbp': { from: 'uk-imports-synthetic-indigo-value', label: 'Synthetic indigo', unit: '£ (nominal)', geography: 'United Kingdom imports' },
    'india-price-index': { from: 'india-natural-indigo-export-unit-value', label: 'Natural: India export value per cwt', unit: 'index, 1897 = 100', geography: 'British India',
                       index: { baseYear: 1897, unit: 'rupees per cwt' } },
    'basf-price-index':  { from: 'basf-synthetic-indigo-price', label: 'Synthetic: BASF price per kg', unit: 'index, 1897 = 100', geography: 'Germany',
                       index: { baseYear: 1897, unit: 'marks per kg' } },
    'tokushima-area': { from: 'tokushima-indigo-area-ha', label: 'Tokushima indigo area', unit: 'hectares', geography: 'Tokushima Prefecture, Japan' },
    'world-synthetic': { from: 'world-synthetic-indigo-output-estimates', label: 'World synthetic indigo (published estimates)', unit: 't/yr', geography: 'World',
                       note: 'Indicative only: no primary industry statistic exists; estimates use different bases.',
                       pointSource: { 1995: 0, 2010: 1, 2011: 2, 2023: 3 },
                       /* 2024 is a market-research figure seen only in search snippets, with no fetchable source. */
                       drop: [2024] },
    'jeans-volume':  { from: 'world-jeans-volume', label: 'World jeans output (published estimates)', unit: 'million units/yr', geography: 'World',
                       pointSource: { 1979: 0, 1989: 1, 2011: 2 } },
  };

  /* ── CHARTS (canvas id → series) ─────────────────────────────────── */
  const charts = [
    { canvas: 'chart-carolina', datasets: [
        { series: 'sc-exports', label: 'South Carolina', color: 'plantation' },
        { series: 'ga-exports', label: 'Georgia', color: 'v6' } ],
      options: { type: 'bar', stacked: true, yTitle: 'Pounds exported (lb)', sourceEl: 'chart-carolina-source' } },
    { canvas: 'chart-atlantic-rivals', datasets: [
        { series: 'sd-to-france-lb', label: 'Saint-Domingue → France (livres → lb)', color: 'plantation', type: 'line' },
        { series: 'sc-exports', label: 'South Carolina exports (lb)', color: 'v5', type: 'line', fill: false },
        { series: 'ca-output', label: 'Central America (libras)', color: 'searoutes', type: 'line', dash: [4, 3] } ],
      options: { type: 'line', yTitle: 'Pounds (lb, or near-equivalent)', sourceEl: 'chart-atlantic-rivals-source' } },
    { canvas: 'chart-arcahaye', datasets: [{ series: 'arcahaye', label: 'Indigo works', color: 'plantation' }],
      options: { type: 'bar', yTitle: 'Indigoteries in the parish', sourceEl: 'chart-arcahaye-source' } },
    { canvas: 'chart-india-long', datasets: [
        { series: 'bengal-output-t', label: 'Bengal output, 1795–1831 (factory maunds → t)', color: 'empire', type: 'bar' },
        { series: 'india-exports-t', label: 'British India exports, 1876–1924 (cwt → t)', color: 'v7', type: 'bar' } ],
      options: { type: 'bar', yTitle: 'Tonnes (converted)', sourceEl: 'chart-india-long-source' } },
    { canvas: 'chart-india-area', datasets: [{ series: 'india-area', label: 'Acres under indigo', color: 'empire' }],
      options: { type: 'bar', yTitle: 'Acres', sourceEl: 'chart-india-area-source' } },
    { canvas: 'chart-uk-bill', datasets: [
        { series: 'uk-natural-gbp', label: 'Natural indigo imports', color: 'empire', type: 'line' },
        { series: 'uk-synthetic-gbp', label: 'Synthetic indigo imports', color: 'synthetic', type: 'line' } ],
      options: { type: 'line', yTitle: '£ (nominal)', sourceEl: 'chart-uk-bill-source' } },
    { canvas: 'chart-price-index', datasets: [
        { series: 'india-price-index', label: 'Natural (India export value per cwt)', color: 'empire', type: 'line' },
        { series: 'basf-price-index', label: 'Synthetic (BASF price per kg)', color: 'synthetic', type: 'line' } ],
      options: { type: 'line', yTitle: 'Index, 1897 = 100', yMin: 0, sourceEl: 'chart-price-index-source' } },
    { canvas: 'chart-tokushima', datasets: [{ series: 'tokushima-area', label: 'Hectares under indigo', color: 'denim' }],
      options: { type: 'bar', yLog: true, yTitle: 'Hectares (log scale)', sourceEl: 'chart-tokushima-source' } },
    { canvas: 'chart-world-output', datasets: [{ series: 'world-synthetic', label: 'World synthetic indigo, t/yr', color: 'revival' }],
      options: { type: 'bar', yTitle: 'Tonnes per year', sourceEl: 'chart-world-output-source' } },
    { canvas: 'chart-sandbox-volume', datasets: [
        { series: 'sd-to-france-t', label: 'Saint-Domingue → France', color: 'plantation', type: 'line' },
        { series: 'sc-exports-t', label: 'South Carolina', color: 'v5', type: 'line', fill: false },
        { series: 'ca-output-t', label: 'Central America', color: 'searoutes', type: 'line' },
        { series: 'bengal-output-t', label: 'Bengal', color: 'empire', type: 'line' },
        { series: 'india-exports-t', label: 'British India exports', color: 'v7', type: 'line' } ],
      options: { type: 'line', yTitle: 'Tonnes (converted)', yearLine: true, legend: false } },
  ];

  /* ── CATEGORY BARS ─────────────────────────────────────────────── */
  const lca = H.quant('levis-501-water-by-phase').value;
  const lcaSrc = qs('levis-501-water-by-phase', 0)[0];
  const barCharts = [
    { canvas: 'chart-water', unit: 'litres', horizontal: true, sourceEl: 'chart-water-source',
      bars: [
        { label: 'Growing the cotton', value: lca.fiber_cotton, color: 'revival' },
        { label: 'Consumer washing', value: lca.consumer_care, color: 'v5' },
        { label: 'Fabric production (incl. dyeing)', value: lca.fabric_production, color: 'denim' },
        { label: 'Sundries & packaging', value: lca.sundries_packaging, color: 'v3' },
        { label: 'Cut, sew, finish', value: lca.cut_sew_finish, color: 'v2' },
      ].map(b => ({ ...b, source: lcaSrc })),
      note: 'Levi Strauss & Co. life-cycle assessment of one pair of 501s (2015): 3,781 litres consumed in total; the phases as read sum to 3,772 L.' },
  ];

  /* ── SANKEYS ───────────────────────────────────────────────────── */
  const voc = ev('voc-indigo-fleet-1631');
  const peak = ev('indian-indigo-peak-1895');
  const sankeys = {
    '1631': {
      label: '1631 · One Dutch fleet',
      headers: ['Indian source', 'Carrier', 'Landed'],
      caption: 'The indigo aboard seven VOC ships that reached Holland from the East Indies in 1631, itemised by Beckmann: 333,545 lb in all. Band widths are pounds.',
      nodes: [
        { name: 'Gujarat ("Guzerat") — 149,730 lb', col: 0, color: 'searoutes' },
        { name: 'Bayana, near Agra — 110,493 lb', col: 0, color: 'v7' },
        { name: 'Sarkhej, Gujarat — 73,322 lb', col: 0, color: 'v6' },
        { name: 'VOC return fleet, 7 ships', col: 1, color: 'v5' },
        { name: 'Holland — 333,545 lb', col: 2, color: 'v5' },
      ],
      links: [
        { source: 0, target: 3, value: 149730, unit: 'lb' },
        { source: 1, target: 3, value: 110493, unit: 'lb' },
        { source: 2, target: 3, value: 73322, unit: 'lb' },
        { source: 3, target: 4, value: 333545, unit: 'lb' },
      ],
      source: voc.map((s, i) => i === 0 ? { ...s, note: 'Beckmann\'s spellings are grouped: "Sirches" and "Chirches" = Sarkhej (13,539 + 32,251 + 27,532 lb); "Guzerat" (82,734 + 66,996); "Bajano" and "Bejana" = Bayana (50,795 + 59,698). The grouping follows the research note; the pounds are Dutch pounds as Beckmann gives them.' } : s),
    },
    '1896': {
      label: '1896–97 · India at the peak',
      headers: ['Province', 'Export hub', 'Market'],
      caption: 'British India\'s indigo exports in 1896–97, the year before synthetic indigo went on sale, by producing province and by market. Band widths are hundredweights (cwt).',
      nodes: [
        { name: 'Bihar & rest of Bengal Presidency — 109,000', col: 0, color: 'empire' },
        { name: 'Madras — 44,000', col: 0, color: 'v7' },
        { name: 'Other provinces — 16,523 (remainder)', col: 0, color: 'v3' },
        { name: 'British India exports — 169,523 cwt', col: 1, color: 'empire' },
        { name: 'United Kingdom — 89,938 (1896 imports)', col: 2, color: 'v5' },
        { name: 'Other markets — 79,585 (remainder)', col: 2, color: 'v3' },
      ],
      links: [
        { source: 0, target: 3, value: 109000, unit: 'cwt' },
        { source: 1, target: 3, value: 44000, unit: 'cwt' },
        { source: 2, target: 3, value: 16523, unit: 'cwt' },
        { source: 3, target: 4, value: 89938, unit: 'cwt' },
        { source: 3, target: 5, value: 79585, unit: 'cwt' },
      ],
      source: [
        ...peak.slice(0, 2),
        pt('british-india-indigo-exports-cwt', 1896),
        { ...pt('uk-imports-natural-indigo-cwt', 1896) },
        { institution: 'Editorial remainder calculation', title: 'Other provinces and other markets', date: '2026-09-23',
          url: 'https://github.com/fritzhand/history-of-indigo/blob/main/tools/editorial.mjs',
          note: 'DERIVED. Other provinces = 169,523 − 109,000 − 44,000; other markets = 169,523 − 89,938. The UK figure is for calendar 1896 and the Indian total for fiscal 1896–97, so the split is approximate.',
          verificationStatus: 'DERIVED', accessType: 'FREE' },
      ],
    },
    'today': {
      label: '2010s · The synthetic chain',
      headers: ['Where it comes from', 'World indigo', 'What it dyes'],
      caption: 'Shares of today\'s indigo by origin and by use. Band widths are percentages of world output, which published estimates put between 50,000 and 88,000 tonnes a year.',
      nodes: [
        { name: 'Synthetic, aniline route — ≈99%', col: 0, color: 'synthetic' },
        { name: 'Plant indigo — ≈1%', col: 0, color: 'revival' },
        { name: 'World indigo, 50,000–88,000 t/yr (estimates)', col: 1, color: 'v5' },
        { name: 'Denim — more than 95%', col: 2, color: 'denim' },
        { name: 'Other textiles, craft, art — the rest', col: 2, color: 'v3' },
      ],
      links: [
        { source: 0, target: 2, value: 99, unit: '%' },
        { source: 1, target: 2, value: 1, unit: '%' },
        { source: 2, target: 3, value: 95, unit: '%' },
        { source: 2, target: 4, value: 5, unit: '%' },
      ],
      source: [
        ...qs('natural-share-of-indigo'),
        ...qs('share-of-indigo-for-denim').slice(1),
        { institution: 'Editorial share model', title: 'Rounded shares', date: '2026-09-23',
          url: 'https://github.com/fritzhand/history-of-indigo/blob/main/tools/editorial.mjs',
          note: 'DERIVED. Plant indigo ≈1% (Fibershed, itself hedged "said to"); denim "more than 95%" (C&EN 2011), drawn at 95. Output range from the published estimates in the Today section.',
          verificationStatus: 'DERIVED', accessType: 'FREE' },
      ],
    },
  };

  /* ── WHO GREW THE BLUE ─────────────────────────────────────────── */
  const coercion = [
    { place: 'Kingdom of Guatemala (Guatemala, San Salvador)', years: '1549–1636', system: 'Indigenous forced labour in fermentation obrajes; enslaved Africans brought in',
      figure: '85 quintals', figureLabel: 'of indigo for ten Angolan captives, 30 April 1624',
      summary: 'Royal orders of 1549, 1581 and 1636 barred Indigenous workers from the notoriously deadly indigo vats and called for enslaved Africans instead. Owners kept using Indigenous labour and paid the fines; the 1636 ban lasted a week. Indigo also served as money: slaves, houses and dowries were priced in quintals of it.',
      source: [...ev('guatemala-indigo-labor-law-1581', [0]), ...ev('indigo-currency-guatemala-1624', [0]), ...ev('quinones-autos-1636', [0])] },
    { place: 'South Carolina Lowcountry', years: '1747–1775', system: 'Chattel slavery',
      figure: '15 + 25', figureLabel: 'enslaved hands to grow and to process 50 acres (Woodmason, 1755)',
      summary: 'Planting, weeding, harvesting and the skilled steeping and beating were done almost entirely by enslaved people of African descent; a skilled "indigo maker" decided whether a year\'s crop was good. The colony\'s export statistics are, in effect, a measure of coerced African labour and skill.',
      source: ev('enslaved-indigo-makers-carolina') },
    { place: 'West African coast (Senegambia to the Bight of Benin)', years: 'mid-18th century', system: 'Indian indigo cloth as currency in the Atlantic slave trade',
      figure: '≈30%', figureLabel: 'Indian piece goods\' share of Anglo-African export value',
      summary: 'Indigo-dyed Indian cottons — "blue goods", guinées, bafts, nicanees — bought captives from African brokers; in the Senegal River region Indian cloth became a regional currency, its indigo smell used to authenticate it. The cloth that bought people linked Asian dyers directly to the plantations of the Americas.',
      source: ev('guinea-cloth-slave-trade-1765') },
    { place: 'Saint-Domingue (Haiti)', years: 'to 1789', system: 'Chattel slavery on indigo works; many owned by free people of colour',
      figure: '3,150', figureLabel: 'indigoteries counted in 1789',
      summary: 'Indigo needed less capital than sugar, so indigo works multiplied, and many belonged to free people of colour; in older districts irrigation turned them into sugar estates. The labour on both was enslaved.',
      source: ev('saint-domingue-3150-indigoteries-1789') },
    { place: 'Lower Bengal (Nadia, Jessore, Barasat)', years: '1830–1860', system: 'Ryoti advances: cash loans against compulsory sowing',
      figure: '49', figureLabel: 'serious cases (murder, riot, arson, kidnapping) 1830–59, put to the 1860 Commission',
      summary: 'Advances rarely covered costs, so debts piled up and passed down through families; the magistrate Ashley Eden told the Commission cultivation was "always compulsory". The ryots\' refusal to sow in 1859 ended the industry in Lower Bengal.',
      source: [...ev('ryoti-advance-system'), ...ev('indigo-revolt-1859', [0])] },
    { place: 'Bihar — Champaran and Tirhut', years: '1868–1918', system: 'Tinkathia: tenants bound to plant indigo on part of their land',
      figure: '3/20', figureLabel: 'of a tenant\'s land owed to indigo',
      summary: 'After Bengal the industry moved to Bihar, where the obligation was cut from 6 to 3 kathas per bigha in 1867–68. Gandhi\'s 1917 inquiry took nearly 4,000 statements; the Champaran Agrarian Act of 4 March 1918 abolished tinkathia and ordered refunds of unlawful exactions.',
      source: [...ev('industry-moves-to-bihar-tinkathia', [0]), ...ev('champaran-satyagraha-1917', [0, 1]), ...ev('champaran-agrarian-act-1918', [0])] },
    { place: 'British India (chiefly Bihar)', years: '1901–1903', system: 'Factory wage labour lost to synthetic indigo',
      figure: '173,000 → 82,000', figureLabel: 'people employed in indigo factories',
      summary: 'Excluding small vats, India had 923 indigo factories employing 173,000 people in 1901 and 531 employing 82,000 in 1903. The Imperial Gazetteer reckoned the industry\'s loss would take part-year work from 250,000 people.',
      source: qs('india-indigo-factories-1901-1903') },
    { place: 'Abeokuta (Egba Yoruba), Nigeria', years: '1930s', system: 'Women\'s adire dyeing workshops',
      figure: '1937–39', figureLabel: 'collapse of the adire industry',
      summary: 'In the Depression, newcomers using synthetic indigo and caustic soda undercut quality; the Alake banned both, and the women dyers hired lawyers and petitioned colonial officials. Their industry collapsed in 1937–39.',
      source: ev('adire-collapse-1930s') },
    { place: 'Xintang and Gurao, Guangdong, China', years: '2010', system: 'Denim dyeing and finishing clusters',
      figure: '128×', figureLabel: 'China\'s cadmium limit, in one river sample',
      summary: 'Greenpeace found five heavy metals in 17 of 21 water and sediment samples; satellite images showed the Pearl River running black past Xintang, which made about 200 million pairs of jeans a year.',
      source: ev('xintang-pearl-river-pollution') },
    { place: 'Dhaka (Savar), Bangladesh', years: '2020', system: 'Garment and denim washing effluent',
      figure: '$34B', figureLabel: 'garment exports, 2019 — second only to China',
      summary: 'Rivers and canals near Dhaka\'s garment districts ran black with dyeing and finishing effluent; the environment ministry ordered every polluting facility to install and run treatment plants.',
      source: ev('dhaka-savar-black-rivers') },
  ];

  /* ── REGION MATRIX ─────────────────────────────────────────────── */
  const regionImpact = [
    { region: 'Toulouse & the Lauragais', years: '1463–1562', role: 'Woad grower & exporter', net: 'Collapsed',
      cost: 'The "pays de cocagne" shipped up to 200,000 bales of woad a year from Bordeaux in the sixteenth century; the merchant Pierre d\'Assézat built his Toulouse mansion in 1555–62. The trade broke after 1561: poor harvests, the Wars of Religion from 1562 and imported indigo.',
      source: [...ev('toulouse-pastel-golden-age', [0]), ...ev('toulouse-pastel-boom-and-bust', [0])] },
    { region: 'Thuringia (Erfurt)', years: '13th–17th c.', role: 'Woad grower & processor', net: 'Collapsed',
      cost: 'Five woad towns processed Europe\'s blue; the imperial ban on indigo (1654) delayed but did not stop the decline. Erfurt\'s woad was grown in 49 villages in 1579; by 1747 only 15 villages across Erfurt and Gotha still grew it.',
      source: [...ev('erfurt-woad-towns-university', [0]), ...qs('erfurt-woad-villages-1579'), ...qs('erfurt-gotha-woad-villages-1747')] },
    { region: 'Kingdom of Guatemala', years: '16th–19th c.', role: 'Añil grower & exporter', net: 'Coerced',
      cost: 'Twenty-one Guatemala City merchants exported almost 2.5 million lb in 1778–85, about 60% of production, and a growers\' fund was founded in 1782; Indigenous and enslaved African workers bore the obrajes.',
      source: [...ev('guatemala-indigo-merchants-1778', [0]), ...ev('montepio-cosecheros-anil-1782', [0]), ...ev('guatemala-indigo-labor-law-1581', [0])] },
    { region: 'South Carolina & Georgia', years: '1747–1788', role: 'Bounty-backed plantation exporter', net: 'Enslaved',
      cost: 'Planters earned a British bounty of sixpence a pound and indigo became the colony\'s second export after rice; enslaved Africans did the work. The bounty lapsed in 1777; exports recovered partly after 1783, then fell as Britain turned to Bengal and planters moved to cotton.',
      source: [...ev('parliament-indigo-bounty-1748', [0]), ...ev('carolina-indigo-peak-1775', [0]), ...ev('revolution-ends-indigo-bounty-1777', [0])] },
    { region: 'Saint-Domingue', years: 'to 1791', role: 'Largest Atlantic producer', net: 'Enslaved',
      cost: 'Indigo shipments to France topped four million livres in 1771–72; 3,150 indigoteries in 1789 gave free people of colour a route to landholding, on enslaved labour.',
      source: [...ev('saint-domingue-indigo-peak-1771', [0]), ...ev('saint-domingue-3150-indigoteries-1789', [0])] },
    { region: 'Lower Bengal', years: 'c. 1777–1860s', role: 'Company plantation economy', net: 'Revolted',
      cost: 'The East India Company, its officials and Calcutta agency houses used indigo to send salaries and profits home; ryots paid through debt and violence. Their 1859–60 revolt ended the industry in Lower Bengal.',
      source: [...ev('company-revives-bengal-indigo', [0]), ...ev('ryoti-advance-system', [0]), ...ev('indigo-revolt-1859', [0])] },
    { region: 'Bihar / Tirhut (Champaran)', years: '1860s–1918', role: 'Planter estates on tenant land', net: 'Collapsed',
      cost: 'European planters once earned 25–35% on capital; tenants carried tinkathia. Synthetic indigo cut the four districts\' indigo area by more than 90% between 1894–95 and 1914–15, and Gandhi\'s 1917 campaign ended tinkathia.',
      source: [...ev('industry-moves-to-bihar-tinkathia', [0]), ...ev('india-natural-indigo-collapse', [0]), ...ev('champaran-satyagraha-1917', [0])] },
    { region: 'Ludwigshafen & Höchst', years: '1897–2023', role: 'Synthetic inventor & producer', net: 'Transformed',
      cost: 'BASF and Hoechst exported 10,000 t of synthetic indigo in 1913 and ended the plantation trade within two decades. Production passed to DyStar and then to China; the Ludwigshafen plant closed in 2023.',
      source: [...ev('german-synthetic-indigo-peak-1913', [0]), ...ev('dystar-ludwigshafen-closure', [0])] },
    { region: 'Tokushima (Awa), Japan', years: '1700s–today', role: 'Sukumo grower & processor', net: 'Persisted',
      cost: 'Awa sukumo led Japan\'s market to a peak of about 15,000 ha in 1903; imported Indian and synthetic indigo cut it to 4 ha by 1965. Today 56 households make about 37 t of sukumo a year for a heritage market.',
      source: [...ev('awa-indigo-peak-1903', [0]), ...ev('tokushima-sukumo-2024', [0])] },
    { region: 'Kano, Hausaland', years: 'c. 1498–today', role: 'Dyer, weaver & trader', net: 'Endured',
      cost: 'In 1851 Barth put Kano\'s cloth sold abroad at no less than 300 million cowries a year, with more than 2,000 dye pots each taxed 700 cowries. A reduced number of pits survives at Kofar Mata.',
      source: [...ev('barth-kano-cloth-trade-1851', [0]), ...ev('kofar-mata-dye-pits-1498', [0])] },
    { region: 'Abeokuta (Egba Yoruba)', years: '1890s–1940', role: 'Women\'s adire industry', net: 'Collapsed',
      cost: 'Women dyers built an export industry in adire across West and Central Africa on credit and imported cloth, then lost it in the Depression to synthetic dye, caustic soda and a political fight over both.',
      source: [...ev('adire-eleko-abeokuta', [0]), ...ev('adire-collapse-1930s', [0])] },
    { region: 'Xintang & the Pearl River Delta', years: '2000s–today', role: 'Denim manufacturing hub', net: 'Polluted',
      cost: 'About 200 million pairs of jeans a year in 2010, and a river running black; heavy metals in 17 of 21 samples. Most of the world\'s indigo is now made in China.',
      source: [...ev('xintang-pearl-river-pollution', [0]), ...ev('dystar-ludwigshafen-closure', [0])] },
    { region: 'Tennessee (Stony Creek Colors)', years: '2012–today', role: 'Plant-indigo revival', net: 'Revived',
      cost: 'Former tobacco farmers grow indigo for a pre-reduced plant dye; acreage rose from 30 acres in 2016 to about 500 across three states by 2022, with Levi Strauss & Co. as an investor.',
      source: ev('stony-creek-colors', [0, 1]) },
  ].filter(r => r.region);

  /* ── PLANTS ────────────────────────────────────────────────────── */
  const plantSrc = (id, n = 2) => (H.plant(id).sources || []).slice(0, n).map(s => H.cleanSource(s));
  const plants = [
    { id: 'indigofera-tinctoria', latin: 'Indigofera tinctoria', name: 'True indigo', color: 'empire', media: 'indigofera-tinctoria-plant',
      regions: 'South Asia · now pantropical',
      note: 'The source of "Indian" indigo, from Pliny\'s indicum to the factories of Bengal and Bihar. A 2025 study puts its extraction yield at about five times woad\'s.',
      source: plantSrc('indigofera-tinctoria') },
    { id: 'indigofera-suffruticosa', latin: 'Indigofera suffruticosa', name: 'Añil · xiquilite', color: 'searoutes', media: 'anil-indigofera-suffruticosa',
      regions: 'Tropical Americas',
      note: 'The native American indigo: xiquilite of the Guatemalan obrajes and the Caribbean, and a candidate source for Maya Blue.',
      source: plantSrc('indigofera-suffruticosa') },
    { id: 'isatis-tinctoria', latin: 'Isatis tinctoria', name: 'Woad', color: 'medieval', media: 'woad-isatis-tinctoria-plant',
      regions: 'Europe · West Asia',
      note: 'A cabbage relative, and Europe\'s blue from the Bronze Age to the seventeenth century. It paid for cities and lost to tropical indigo once ships could carry it.',
      source: plantSrc('isatis-tinctoria') },
    { id: 'persicaria-tinctoria', latin: 'Persicaria tinctoria', name: 'Japanese indigo · dyer\'s knotweed', color: 'denim', media: 'japanese-indigo-persicaria-tinctoria',
      regions: 'China · Japan',
      note: 'The "ai" of the Shōsōin treasures and of Tokushima\'s sukumo, the composted leaf still made for Japanese vats.',
      source: plantSrc('persicaria-tinctoria') },
    { id: 'strobilanthes-cusia', latin: 'Strobilanthes cusia', name: 'Assam indigo', color: 'revival', media: 'assam-indigo-strobilanthes-cusia',
      regions: 'Eastern Himalaya · South China · SE Asia',
      note: 'An acanthus, unrelated to the legumes, that supplies indigo from the eastern Himalaya to southern China and mainland Southeast Asia.',
      source: plantSrc('strobilanthes-cusia') },
    { id: 'philenoptera-cyanescens', latin: 'Philenoptera cyanescens', name: 'Gara · West African indigo', color: 'origins',
      regions: 'West Africa',
      note: 'A climbing legume used for indigo in West Africa since at least the eleventh century; residues cannot tell it from Indigofera in the Tellem cloths.',
      source: plantSrc('philenoptera-cyanescens') },
  ];

  /* ── CHEMISTRY ─────────────────────────────────────────────────
     Four stages for the vat diagram, condensed from the research pass's
     ten chemistry steps; each keeps the sources of the steps it condenses. */
  const cs = i => H.chemStepSource(i);
  const chemistry = {
    formula: 'C₁₆H₁₀N₂O₂',
    molarMass: '262.26 g/mol',
    note: 'Tyrian purple, the other ancient "royal" dye, is 6,6′-dibromoindigo: the same skeleton with two bromine atoms',
    source: [H.chemFormulaSource()],
    steps: [
      { icon: 'leaf', kicker: 'Stage 1 · In the leaf', title: 'A colourless precursor',
        body: 'Indigo plants hold no blue. Their leaves store 0.2–0.8% of indican, a colourless, sugar-bound form of indoxyl.',
        source: [cs(0)] },
      { icon: 'steep', kicker: 'Stage 2 · Steep', title: 'Fermentation frees indoxyl',
        body: 'Steeping the cut plants in water lets an enzyme cut the sugar away, releasing reactive indoxyl into the liquor.',
        source: [cs(1)] },
      { icon: 'beat', kicker: 'Stage 3 · Beat', title: 'Air makes the blue',
        body: 'Beaten or aerated, two indoxyl units join into indigotin. It does not dissolve in water, so it settles as a blue mud that is dried into cakes — and cannot dye cloth by soaking alone.',
        source: [cs(2), cs(3)] },
      { icon: 'dip', kicker: 'Stage 4 · Vat', title: 'Reduce, dip, air, repeat',
        body: 'An alkaline vat reduces indigo to yellow, soluble leuco-indigo — for millennia by fermentation, since 1906 mainly with sodium dithionite. Cloth leaves the vat yellow-green, turns blue in the air, and darkens with every dip.',
        source: [cs(4), cs(5)] },
    ],
  };

  /* ── HERO & FOOTER ─────────────────────────────────────────────── */
  const heroStats = [
    { value: '≈6,000', label: 'years since the oldest indigo-dyed cloth', sublabel: 'Huaca Prieta, Peru', color: 'origins',
      source: ev('huaca-prieta-indigo-cotton', [0]) },
    { value: '1.7M', label: 'acres under indigo in British India', sublabel: '1,705,977 in 1894–95, the natural crop\'s peak', color: 'empire',
      source: [pt('british-india-indigo-area', 1894)] },
    { value: '1897', label: 'BASF\'s synthetic Indigo Pure goes on sale', sublabel: '10 July, at 16 marks/kg against 20 for natural', color: 'synthetic',
      source: ev('basf-indigo-pure-launch', [0]) },
    { value: '3,781 L', label: 'water per pair of Levi\'s 501s', sublabel: '2015 life-cycle study; 68% grows the cotton', color: 'denim',
      source: [lcaSrc] },
  ];
  const footerStats = [
    { value: '107,000', label: 'acres under indigo in British India, 1924–25', sublabel: '−94% from the 1894–95 peak', color: 'empire',
      source: [pt('british-india-indigo-area', 1924)] },
    { value: '99%', label: 'of indigo went to denim', sublabel: 'BASF\'s indigo chief, 1997', color: 'denim',
      source: qs('share-of-indigo-for-denim', [0]) },
    { value: '37 t', label: 'Tokushima sukumo, FY2024', sublabel: '56 households keep the leaf vat alive', color: 'revival',
      source: ev('tokushima-sukumo-2024', [0]) },
    { value: '2018', label: 'UNESCO lists Europe\'s indigo resist printing', sublabel: 'Blaudruck, five countries', color: 'v5',
      source: ev('unesco-blaudruck-inscription', [0]) },
  ];

  return {
    meta, events, scrollSteps, series, charts, barCharts, sankeys, coercion, regionImpact, plants, chemistry,
    heroStats, footerStats,
    mediaDrop: [],
    /* Caption corrections where the picture research's wording overstated or
       conflicted with the event research. */
    mediaOverrides: {
      'adolf-von-baeyer-portrait': { caption: 'Adolf von Baeyer (1835–1917) first made indigo in the laboratory in 1878, found further routes in 1880–82 and sent BASF its structural formula in 1883; he received the 1905 Nobel Prize in Chemistry. Portrait as published in Popular Science Monthly.' },
      'basf-ludwigshafen-1881': { caption: 'Robert Stieler\'s painting of the Badische Anilin- & Soda-Fabrik works in 1881, a year after BASF bought Baeyer\'s 1880 indigo patent. An industrial route took the company seventeen years; synthetic indigo went on sale in 1897.' },
      'levi-strauss-davis-rivet-patent-1873': { caption: 'Jacob W. Davis\'s patent drawing for riveting the pocket corners of work trousers, granted on 20 May 1873 to Davis as assignor to himself and Levi Strauss & Co. Riveted trousers of indigo-dyed denim became the blue jeans that now absorb almost all the world\'s indigo.' },
      'simpson-indigo-factory-bengal-1867': { caption: 'William Simpson\'s view of a Bengal indigo works, with its chimney, bungalow and rows of vats, reproduced as a chromolithograph in India: Ancient and Modern (1867), less than a decade after the Indigo Revolt.' },
      'faden-carolina-map-cartouche-1780': { caption: 'The title cartouche of William Faden\'s 1780 map of South Carolina and part of Georgia shows enslaved men processing indigo, the colony\'s second export after rice.' },
    },
    mediaOrder: [],
  };
}
